syntax = "proto3";

import "google/protobuf/timestamp.proto";

package donaciones;

message Donaciones{
    int64 iddonaciones = 1;
    string categoria = 2;
    string descripcion = 3;
    int32 cantidad = 4;
    bool eliminado = 5;
    google.protobuf.Timestamp fecha_alta = 6;
    google.protobuf.Timestamp fecha_mod = 7;
    int64 usuario_alta = 8;
    int64 usuario_mod = 9;
}

message AltaDonacionesRequest{
    Donaciones donaciones = 1;
}

message AltaDonacionesResponse{
    bool suceso = 1;
}

message ModDonacionesRequest{
    Donaciones donaciones = 1;
}

message ModDonacionesResponse{
    bool suceso = 1;
}

message BajaDonacionesRequest{
    int64 iddonaciones = 1;
}

message BajaDonacionesResponse{
    bool suceso = 1;
}

message Empty{}

message ListDonacionesResponse{
    repeated Donaciones donaciones = 1;
}

// Kafka Solicitudes

// Solicitar
message DonacionSolicitada{
    string categoria = 1;
    string descripcion = 2;
}

message SolicitarDonacionRequest{
    int64 idSolicitante = 1;
    int64 idOrganizacion = 2;
    repeated DonacionSolicitada donacion = 3;
}

message SolicitarDonacionResponse{
    bool suceso = 1;
}

// Transferir
    message DonacionTransferida{
    string categoria = 1;
    string descripcion = 2;
    int64 cantidad = 3;
}

message TransferirDonacionRequest{
    int64 idSolicitud = 1;
    int64 idOrganizacionDonante = 2;
    int64 idOrganizacionSolicitante = 3;
    repeated DonacionTransferida donacion = 4;
}
message TransferirDonacionResponse{
    bool suceso = 1;
}

service DonacionesService{
    rpc GetDonaciones(Empty) returns (ListDonacionesResponse);
    rpc AltaDonaciones(AltaDonacionesRequest) returns (AltaDonacionesResponse);
    rpc ModDonaciones(ModDonacionesRequest) returns (ModDonacionesResponse);
    rpc BajaDonaciones(BajaDonacionesRequest) returns (BajaDonacionesResponse);

    rpc SolicitarDonacion(SolicitarDonacionRequest) returns (SolicitarDonacionResponse);
    rpc TransferirDonacion(TransferirDonacionRequest) returns (TransferirDonacionResponse);
}