syntax = "proto3";

import "google/protobuf/timestamp.proto";

package eventos;

message EventosDTO{
    string nombre = 1;
    string descripcion = 2;
    google.protobuf.Timestamp fecha = 3;
}

message Eventos{
    int64 ideventos = 1;
    string nombre = 2;
    string descripcion = 3;
    google.protobuf.Timestamp fecha = 4;
    repeated Usuario usuario = 5;
}

message AltaEventoRequest{
    EventosDTO evento = 1;
}

message AltaEventoResponse{
    Eventos evento = 1;
}

message ModEventoRequest{
    Eventos evento = 1;
}

message ModEventoResponse{
    Eventos evento = 1;
}

message BajaEventoRequest{
    int64 ideventos = 1;
}

message BajaEventoResponse{
    Eventos evento = 1;
}

message AsignarMiembroRequest{
    int64 idusuario = 1;
    int64 ideventos = 2;
}

message QuitarMiembroRequest{
    int64 idusuario = 1;
    int64 ideventos = 2;
}

message Empty{}

message ListEventosResponse{
    repeated EventosDTO evento = 1;
}

service EventosService{
    rpc GetEventos(Empty) returns (ListEventosResponse);
    rpc AltaEvento(AltaDonacionesRequest) returns (AltaDonacionesResponse);
    rpc ModEvento(ModDonacionesRequest) returns (ModEventoResponse);
    rpc BajaEvento(BajaDonacionesRequest) returns (BajaEventoResponse);
    rpc AgregarMiembro(AsignarMiembroRequest) returns (Empty);
    rpc QuitarMiembro(QuitarMiembroRequest) returns (Empty);
}