syntax = "proto3";

import "google/protobuf/timestamp.proto";

import "usuarios.proto";
import "donaciones.proto";

package eventos;

message Eventos{
    int64 ideventos = 1;
    string nombre = 2;
    string descripcion = 3;
    google.protobuf.Timestamp fechaHora = 4;
    repeated usuarios.Usuario usuario = 5;

    repeated DonarEvento donar = 6;
}

message AltaEventoRequest{
    Eventos evento = 1;
}

message AltaEventoResponse{
    bool suceso = 1;
}

message ModEventoRequest{
    Eventos evento = 1;
    repeated donaciones.Donaciones donaciones = 2;
}

message ModEventoResponse{
    bool suceso = 1;
}

message BajaEventoRequest{
    int64 ideventos = 1;
}

message BajaEventoResponse{
    bool suceso = 1;
}

message DonarEvento{
    int64 iddonaciones = 1;
    int64 ideventos = 2;
    int64 cantidad_donada = 3;
}

message DonarRequest{
    DonarEvento donar = 1;
}

message DonarResponse{
    bool suceso = 1;
}

message Empty{}

message ListEventosResponse{
    repeated Eventos evento = 1;
}

service EventosService{
    rpc GetEventos(Empty) returns (ListEventosResponse);
    rpc AltaEvento(AltaEventoRequest) returns (AltaEventoResponse);
    rpc ModEvento(ModEventoRequest) returns (ModEventoResponse);
    rpc BajaEvento(BajaEventoRequest) returns (BajaEventoResponse);
    rpc DonarEvento(DonarRequest) returns (DonarResponse);
}