syntax = "proto3";

package usuarios;

//  DTO para alta

message UsuarioDTO {
  string nombreUsuario = 2;
  string nombre = 3;
  string apellido = 4;
  string email = 5;
}

// Usuario para modificacion y validacion

message Usuario {
  int64 idusuario = 1;
  string nombreUsuario = 2;
  string nombre = 3;
  string apellido = 4;
  string email = 5;
  int64 rol = 6;
  string clave = 7;
  string telefono = 8;
  bool activo = 9;
}

message AltaUsuarioRequest {
  UsuarioDTO usuario = 1;
}

message AltaUsuarioResponse {
  Usuario usuario = 1;
}

message ModUsuarioRequest {
  Usuario usuario = 1;
}

message ModUsuarioResponse {
  Usuario usuario = 1;
}

message BajaUsuarioRequest {
  int64 idusuario = 1;
}

message BajaUsuarioResponse {
  Usuario usuario = 1;
}

message Empty {}

message UsuarioListResponse {
  repeated UsuarioDTO usuarios = 1;
}

service UsuarioService {
  rpc GetUsuarios (Empty) returns (UsuarioListResponse);
  rpc AltaUsuario (AltaUsuarioRequest) returns (AltaUsuarioResponse);
  rpc ModUsuario (ModUsuarioRequest) returns (ModUsuarioResponse);
  rpc BajaUsuario (BajaUsuarioRequest) returns (BajaUsuarioResponse);
}