# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cosas.proto

require 'google/protobuf'


descriptor_data = "\n\x0b\x63osas.proto\"\x07\n\x05\x45mpty\"\'\n\x06RolDTO\x12\r\n\x05idrol\x18\x01 \x01(\x03\x12\x0e\n\x06nombre\x18\x02 \x01(\t\")\n\x0fRolListResponse\x12\x16\n\x05roles\x18\x01 \x03(\x0b\x32\x07.RolDTO2R\n\nRolService\x12$\n\x08getRoles\x12\x06.Empty\x1a\x10.RolListResponse\x12\x1e\n\x0bupdateRoles\x12\x07.RolDTO\x1a\x06.Emptyb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

Empty = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Empty").msgclass
RolDTO = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("RolDTO").msgclass
RolListResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("RolListResponse").msgclass
