# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: cosas.proto for package ''

require 'grpc'
require 'cosas_pb'

module RolService
  class Service

    include ::GRPC::GenericService

    self.marshal_class_method = :encode
    self.unmarshal_class_method = :decode
    self.service_name = 'RolService'

    rpc :getRoles, ::Empty, ::RolListResponse
    rpc :updateRoles, ::RolDTO, ::Empty
  end

  Stub = Service.rpc_stub_class
end
