# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: donaciones.proto for package 'donaciones'

require 'grpc'
require 'donaciones_pb'

module Donaciones
  module DonacionesService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'donaciones.DonacionesService'

      rpc :GetDonaciones, ::Donaciones::Empty, ::Donaciones::ListDonacionesResponse
      rpc :AltaDonaciones, ::Donaciones::AltaDonacionesRequest, ::Donaciones::AltaDonacionesResponse
      rpc :ModDonaciones, ::Donaciones::ModDonacionesRequest, ::Donaciones::ModDonacionesResponse
      rpc :BajaDonaciones, ::Donaciones::BajaDonacionesRequest, ::Donaciones::BajaDonacionesResponse
      # Kafka Solicitudes
      rpc :SolicitarDonacion, ::Donaciones::SolicitarDonacionRequest, ::Donaciones::SolicitarDonacionResponse
    end

    Stub = Service.rpc_stub_class
  end
end
