# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: donaciones.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'


descriptor_data = "\n\x10\x64onaciones.proto\x12\ndonaciones\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf9\x01\n\nDonaciones\x12\x14\n\x0ciddonaciones\x18\x01 \x01(\x03\x12\x11\n\tcategoria\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scripcion\x18\x03 \x01(\t\x12\x10\n\x08\x63\x61ntidad\x18\x04 \x01(\x05\x12\x11\n\teliminado\x18\x05 \x01(\x08\x12.\n\nfecha_alta\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12-\n\tfecha_mod\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x14\n\x0cusuario_alta\x18\x08 \x01(\x03\x12\x13\n\x0busuario_mod\x18\t \x01(\x03\"C\n\x15\x41ltaDonacionesRequest\x12*\n\ndonaciones\x18\x01 \x01(\x0b\x32\x16.donaciones.Donaciones\"(\n\x16\x41ltaDonacionesResponse\x12\x0e\n\x06suceso\x18\x01 \x01(\x08\"B\n\x14ModDonacionesRequest\x12*\n\ndonaciones\x18\x01 \x01(\x0b\x32\x16.donaciones.Donaciones\"\'\n\x15ModDonacionesResponse\x12\x0e\n\x06suceso\x18\x01 \x01(\x08\"-\n\x15\x42\x61jaDonacionesRequest\x12\x14\n\x0ciddonaciones\x18\x01 \x01(\x03\"(\n\x16\x42\x61jaDonacionesResponse\x12\x0e\n\x06suceso\x18\x01 \x01(\x08\"\x07\n\x05\x45mpty\"D\n\x16ListDonacionesResponse\x12*\n\ndonaciones\x18\x01 \x03(\x0b\x32\x16.donaciones.Donaciones2\xe3\x02\n\x11\x44onacionesService\x12\x46\n\rGetDonaciones\x12\x11.donaciones.Empty\x1a\".donaciones.ListDonacionesResponse\x12W\n\x0e\x41ltaDonaciones\x12!.donaciones.AltaDonacionesRequest\x1a\".donaciones.AltaDonacionesResponse\x12T\n\rModDonaciones\x12 .donaciones.ModDonacionesRequest\x1a!.donaciones.ModDonacionesResponse\x12W\n\x0e\x42\x61jaDonaciones\x12!.donaciones.BajaDonacionesRequest\x1a\".donaciones.BajaDonacionesResponseb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Donaciones
  Donaciones = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("donaciones.Donaciones").msgclass
  AltaDonacionesRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("donaciones.AltaDonacionesRequest").msgclass
  AltaDonacionesResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("donaciones.AltaDonacionesResponse").msgclass
  ModDonacionesRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("donaciones.ModDonacionesRequest").msgclass
  ModDonacionesResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("donaciones.ModDonacionesResponse").msgclass
  BajaDonacionesRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("donaciones.BajaDonacionesRequest").msgclass
  BajaDonacionesResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("donaciones.BajaDonacionesResponse").msgclass
  Empty = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("donaciones.Empty").msgclass
  ListDonacionesResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("donaciones.ListDonacionesResponse").msgclass
end
