# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eventos.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
require 'usuarios_pb'


descriptor_data = "\n\reventos.proto\x12\x07\x65ventos\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x0eusuarios.proto\"\\\n\nEventosDTO\x12\x0e\n\x06nombre\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scripcion\x18\x02 \x01(\t\x12)\n\x05\x66\x65\x63ha\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\x90\x01\n\x07\x45ventos\x12\x11\n\tideventos\x18\x01 \x01(\x03\x12\x0e\n\x06nombre\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scripcion\x18\x03 \x01(\t\x12)\n\x05\x66\x65\x63ha\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\"\n\x07usuario\x18\x05 \x03(\x0b\x32\x11.usuarios.Usuario\"8\n\x11\x41ltaEventoRequest\x12#\n\x06\x65vento\x18\x01 \x01(\x0b\x32\x13.eventos.EventosDTO\"6\n\x12\x41ltaEventoResponse\x12 \n\x06\x65vento\x18\x01 \x01(\x0b\x32\x10.eventos.Eventos\"4\n\x10ModEventoRequest\x12 \n\x06\x65vento\x18\x01 \x01(\x0b\x32\x10.eventos.Eventos\"5\n\x11ModEventoResponse\x12 \n\x06\x65vento\x18\x01 \x01(\x0b\x32\x10.eventos.Eventos\"&\n\x11\x42\x61jaEventoRequest\x12\x11\n\tideventos\x18\x01 \x01(\x03\"6\n\x12\x42\x61jaEventoResponse\x12 \n\x06\x65vento\x18\x01 \x01(\x0b\x32\x10.eventos.Eventos\"=\n\x15\x41signarMiembroRequest\x12\x11\n\tidusuario\x18\x01 \x01(\x03\x12\x11\n\tideventos\x18\x02 \x01(\x03\"<\n\x14QuitarMiembroRequest\x12\x11\n\tidusuario\x18\x01 \x01(\x03\x12\x11\n\tideventos\x18\x02 \x01(\x03\"\x07\n\x05\x45mpty\":\n\x13ListEventosResponse\x12#\n\x06\x65vento\x18\x01 \x03(\x0b\x32\x13.eventos.EventosDTO2\xa0\x03\n\x0e\x45ventosService\x12:\n\nGetEventos\x12\x0e.eventos.Empty\x1a\x1c.eventos.ListEventosResponse\x12\x45\n\nAltaEvento\x12\x1a.eventos.AltaEventoRequest\x1a\x1b.eventos.AltaEventoResponse\x12\x42\n\tModEvento\x12\x19.eventos.ModEventoRequest\x1a\x1a.eventos.ModEventoResponse\x12\x45\n\nBajaEvento\x12\x1a.eventos.BajaEventoRequest\x1a\x1b.eventos.BajaEventoResponse\x12@\n\x0e\x41gregarMiembro\x12\x1e.eventos.AsignarMiembroRequest\x1a\x0e.eventos.Empty\x12>\n\rQuitarMiembro\x12\x1d.eventos.QuitarMiembroRequest\x1a\x0e.eventos.Emptyb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Eventos
  EventosDTO = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("eventos.EventosDTO").msgclass
  Eventos = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("eventos.Eventos").msgclass
  AltaEventoRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("eventos.AltaEventoRequest").msgclass
  AltaEventoResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("eventos.AltaEventoResponse").msgclass
  ModEventoRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("eventos.ModEventoRequest").msgclass
  ModEventoResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("eventos.ModEventoResponse").msgclass
  BajaEventoRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("eventos.BajaEventoRequest").msgclass
  BajaEventoResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("eventos.BajaEventoResponse").msgclass
  AsignarMiembroRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("eventos.AsignarMiembroRequest").msgclass
  QuitarMiembroRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("eventos.QuitarMiembroRequest").msgclass
  Empty = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("eventos.Empty").msgclass
  ListEventosResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("eventos.ListEventosResponse").msgclass
end
