# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: eventos.proto for package 'eventos'

require 'grpc'
require 'eventos_pb'

module Eventos
  module EventosService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'eventos.EventosService'

      rpc :GetEventos, ::Eventos::Empty, ::Eventos::ListEventosResponse
      rpc :AltaEvento, ::Eventos::AltaEventoRequest, ::Eventos::AltaEventoResponse
      rpc :ModEvento, ::Eventos::ModEventoRequest, ::Eventos::ModEventoResponse
      rpc :BajaEvento, ::Eventos::BajaEventoRequest, ::Eventos::BajaEventoResponse
      rpc :DonarEvento, ::Eventos::DonarRequest, ::Eventos::DonarResponse
    end

    Stub = Service.rpc_stub_class
  end
end
