# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: messages.proto for package 'messages'

require 'grpc'
require 'messages_pb'

module Messages
  module MessagesService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'messages.MessagesService'

      # ---- Donaciones ----
      rpc :AltaSolicitudDonacion, ::Messages::SolicitudDonacion, ::Messages::RespuestaDonacion
      rpc :RegistrarTransferencia, ::Messages::TransferenciaDonacion, ::Messages::RespuestaDonacion
      rpc :AltaOferta, ::Messages::OfertaDonacion, ::Messages::RespuestaDonacion
      rpc :BajaSolicitudDonacion, ::Messages::BajaSolicitud, ::Messages::RespuestaDonacion
      # ---- Eventos ----
      rpc :PublicarEventoExterno, ::Messages::EventoExterno, ::Messages::RespuestaEvento
      rpc :BajaEventoExterno, ::Messages::BajaEvento, ::Messages::RespuestaEvento
      rpc :RegistrarAdhesionEvento, ::Messages::AdhesionEvento, ::Messages::RespuestaEvento
    end

    Stub = Service.rpc_stub_class
  end
end
