# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: rol.proto for package 'roles'

require 'grpc'
require 'rol_pb'

module Roles
  module RolService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'roles.RolService'

      rpc :GetRoles, ::Roles::Empty, ::Roles::RolListResponse
      rpc :updateRoles, ::Roles::RolDTO, ::Roles::Empty
    end

    Stub = Service.rpc_stub_class
  end
end
