# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: session.proto

require 'google/protobuf'


descriptor_data = "\n\rsession.proto\x12\x07session\"4\n\x0cLoginRequest\x12\x15\n\rusuario_email\x18\x01 \x01(\t\x12\r\n\x05\x63lave\x18\x02 \x01(\t\"C\n\rLoginResponse\x12\x0e\n\x06suceso\x18\x01 \x01(\x08\x12\x0f\n\x07mensaje\x18\x02 \x01(\t\x12\x11\n\tidusuario\x18\x03 \x01(\x05\"\x0f\n\rlogoutRequest\" \n\x0elogoutResponse\x12\x0e\n\x06suceso\x18\x01 \x01(\x08\x32\x81\x01\n\x0cLoginService\x12\x36\n\x05Login\x12\x15.session.LoginRequest\x1a\x16.session.LoginResponse\x12\x39\n\x06Logout\x12\x16.session.logoutRequest\x1a\x17.session.logoutResponseb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Session
  LoginRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("session.LoginRequest").msgclass
  LoginResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("session.LoginResponse").msgclass
  LogoutRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("session.logoutRequest").msgclass
  LogoutResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("session.logoutResponse").msgclass
end
