# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: session.proto for package 'session'

require 'grpc'
require 'session_pb'

module Session
  module LoginService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'session.LoginService'

      rpc :Login, ::Session::LoginRequest, ::Session::LoginResponse
      rpc :ObtenerInfo, ::Session::InfoRequest, ::Session::InfoResponse
    end

    Stub = Service.rpc_stub_class
  end
end
