# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: usuarios.proto

require 'google/protobuf'


descriptor_data = "\n\x0eusuarios.proto\x12\x08usuarios\"\xc0\x01\n\x07Usuario\x12\x11\n\tidusuario\x18\x01 \x01(\x03\x12\x15\n\rnombreUsuario\x18\x02 \x01(\t\x12\x0e\n\x06nombre\x18\x03 \x01(\t\x12\x10\n\x08\x61pellido\x18\x04 \x01(\t\x12\x12\n\x05\x65mail\x18\x05 \x01(\tH\x00\x88\x01\x01\x12\x0b\n\x03rol\x18\x06 \x01(\x03\x12\x12\n\x05\x63lave\x18\x07 \x01(\tH\x01\x88\x01\x01\x12\x10\n\x08telefono\x18\x08 \x01(\t\x12\x0e\n\x06\x61\x63tivo\x18\t \x01(\x08\x42\x08\n\x06_emailB\x08\n\x06_clave\"8\n\x12\x41ltaUsuarioRequest\x12\"\n\x07usuario\x18\x01 \x01(\x0b\x32\x11.usuarios.Usuario\"C\n\x13\x41ltaUsuarioResponse\x12\x0e\n\x06suceso\x18\x01 \x01(\x08\x12\x12\n\x05\x63lave\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\x08\n\x06_clave\"7\n\x11ModUsuarioRequest\x12\"\n\x07usuario\x18\x01 \x01(\x0b\x32\x11.usuarios.Usuario\"$\n\x12ModUsuarioResponse\x12\x0e\n\x06suceso\x18\x01 \x01(\x08\"\'\n\x12\x42\x61jaUsuarioRequest\x12\x11\n\tidusuario\x18\x01 \x01(\x03\"%\n\x13\x42\x61jaUsuarioResponse\x12\x0e\n\x06suceso\x18\x01 \x01(\x08\"\x07\n\x05\x45mpty\":\n\x13UsuarioListResponse\x12#\n\x08usuarios\x18\x01 \x03(\x0b\x32\x11.usuarios.Usuario\"#\n\x0eUsuarioRequest\x12\x11\n\tidusuario\x18\x01 \x01(\x05\"5\n\x0fUsuarioResponse\x12\"\n\x07usuario\x18\x01 \x01(\x0b\x32\x11.usuarios.Usuario2\xf3\x02\n\x0eUsuarioService\x12\x41\n\nGetUsuario\x12\x18.usuarios.UsuarioRequest\x1a\x19.usuarios.UsuarioResponse\x12=\n\x0bGetUsuarios\x12\x0f.usuarios.Empty\x1a\x1d.usuarios.UsuarioListResponse\x12J\n\x0b\x41ltaUsuario\x12\x1c.usuarios.AltaUsuarioRequest\x1a\x1d.usuarios.AltaUsuarioResponse\x12G\n\nModUsuario\x12\x1b.usuarios.ModUsuarioRequest\x1a\x1c.usuarios.ModUsuarioResponse\x12J\n\x0b\x42\x61jaUsuario\x12\x1c.usuarios.BajaUsuarioRequest\x1a\x1d.usuarios.BajaUsuarioResponseb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Usuarios
  Usuario = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("usuarios.Usuario").msgclass
  AltaUsuarioRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("usuarios.AltaUsuarioRequest").msgclass
  AltaUsuarioResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("usuarios.AltaUsuarioResponse").msgclass
  ModUsuarioRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("usuarios.ModUsuarioRequest").msgclass
  ModUsuarioResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("usuarios.ModUsuarioResponse").msgclass
  BajaUsuarioRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("usuarios.BajaUsuarioRequest").msgclass
  BajaUsuarioResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("usuarios.BajaUsuarioResponse").msgclass
  Empty = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("usuarios.Empty").msgclass
  UsuarioListResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("usuarios.UsuarioListResponse").msgclass
  UsuarioRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("usuarios.UsuarioRequest").msgclass
  UsuarioResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("usuarios.UsuarioResponse").msgclass
end
