# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: usuarios.proto for package 'usuarios'

require 'grpc'
require 'usuarios_pb'

module Usuarios
  module UsuarioService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'usuarios.UsuarioService'

      rpc :GetUsuarios, ::Usuarios::Empty, ::Usuarios::UsuarioListResponse
      rpc :AltaUsuario, ::Usuarios::AltaUsuarioRequest, ::Usuarios::AltaUsuarioResponse
      rpc :ModUsuario, ::Usuarios::ModUsuarioRequest, ::Usuarios::ModUsuarioResponse
      rpc :BajaUsuario, ::Usuarios::BajaUsuarioRequest, ::Usuarios::BajaUsuarioResponse
    end

    Stub = Service.rpc_stub_class
  end
end
