# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import donaciones_pb2 as donaciones__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in donaciones_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DonacionesServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetDonaciones = channel.unary_unary(
                '/donaciones.DonacionesService/GetDonaciones',
                request_serializer=donaciones__pb2.Empty.SerializeToString,
                response_deserializer=donaciones__pb2.ListDonacionesResponse.FromString,
                _registered_method=True)
        self.AltaDonaciones = channel.unary_unary(
                '/donaciones.DonacionesService/AltaDonaciones',
                request_serializer=donaciones__pb2.AltaDonacionesRequest.SerializeToString,
                response_deserializer=donaciones__pb2.AltaDonacionesResponse.FromString,
                _registered_method=True)
        self.ModDonaciones = channel.unary_unary(
                '/donaciones.DonacionesService/ModDonaciones',
                request_serializer=donaciones__pb2.ModDonacionesRequest.SerializeToString,
                response_deserializer=donaciones__pb2.ModDonacionesResponse.FromString,
                _registered_method=True)
        self.BajaDonaciones = channel.unary_unary(
                '/donaciones.DonacionesService/BajaDonaciones',
                request_serializer=donaciones__pb2.BajaDonacionesRequest.SerializeToString,
                response_deserializer=donaciones__pb2.BajaDonacionesResponse.FromString,
                _registered_method=True)
        self.SolicitarDonacion = channel.unary_unary(
                '/donaciones.DonacionesService/SolicitarDonacion',
                request_serializer=donaciones__pb2.SolicitarDonacionRequest.SerializeToString,
                response_deserializer=donaciones__pb2.SolicitarDonacionResponse.FromString,
                _registered_method=True)
        self.TransferirDonacion = channel.unary_unary(
                '/donaciones.DonacionesService/TransferirDonacion',
                request_serializer=donaciones__pb2.TransferirDonacionRequest.SerializeToString,
                response_deserializer=donaciones__pb2.TransferirDonacionResponse.FromString,
                _registered_method=True)


class DonacionesServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetDonaciones(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AltaDonaciones(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ModDonaciones(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BajaDonaciones(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SolicitarDonacion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TransferirDonacion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DonacionesServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetDonaciones': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDonaciones,
                    request_deserializer=donaciones__pb2.Empty.FromString,
                    response_serializer=donaciones__pb2.ListDonacionesResponse.SerializeToString,
            ),
            'AltaDonaciones': grpc.unary_unary_rpc_method_handler(
                    servicer.AltaDonaciones,
                    request_deserializer=donaciones__pb2.AltaDonacionesRequest.FromString,
                    response_serializer=donaciones__pb2.AltaDonacionesResponse.SerializeToString,
            ),
            'ModDonaciones': grpc.unary_unary_rpc_method_handler(
                    servicer.ModDonaciones,
                    request_deserializer=donaciones__pb2.ModDonacionesRequest.FromString,
                    response_serializer=donaciones__pb2.ModDonacionesResponse.SerializeToString,
            ),
            'BajaDonaciones': grpc.unary_unary_rpc_method_handler(
                    servicer.BajaDonaciones,
                    request_deserializer=donaciones__pb2.BajaDonacionesRequest.FromString,
                    response_serializer=donaciones__pb2.BajaDonacionesResponse.SerializeToString,
            ),
            'SolicitarDonacion': grpc.unary_unary_rpc_method_handler(
                    servicer.SolicitarDonacion,
                    request_deserializer=donaciones__pb2.SolicitarDonacionRequest.FromString,
                    response_serializer=donaciones__pb2.SolicitarDonacionResponse.SerializeToString,
            ),
            'TransferirDonacion': grpc.unary_unary_rpc_method_handler(
                    servicer.TransferirDonacion,
                    request_deserializer=donaciones__pb2.TransferirDonacionRequest.FromString,
                    response_serializer=donaciones__pb2.TransferirDonacionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'donaciones.DonacionesService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('donaciones.DonacionesService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DonacionesService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetDonaciones(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/donaciones.DonacionesService/GetDonaciones',
            donaciones__pb2.Empty.SerializeToString,
            donaciones__pb2.ListDonacionesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AltaDonaciones(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/donaciones.DonacionesService/AltaDonaciones',
            donaciones__pb2.AltaDonacionesRequest.SerializeToString,
            donaciones__pb2.AltaDonacionesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ModDonaciones(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/donaciones.DonacionesService/ModDonaciones',
            donaciones__pb2.ModDonacionesRequest.SerializeToString,
            donaciones__pb2.ModDonacionesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BajaDonaciones(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/donaciones.DonacionesService/BajaDonaciones',
            donaciones__pb2.BajaDonacionesRequest.SerializeToString,
            donaciones__pb2.BajaDonacionesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SolicitarDonacion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/donaciones.DonacionesService/SolicitarDonacion',
            donaciones__pb2.SolicitarDonacionRequest.SerializeToString,
            donaciones__pb2.SolicitarDonacionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TransferirDonacion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/donaciones.DonacionesService/TransferirDonacion',
            donaciones__pb2.TransferirDonacionRequest.SerializeToString,
            donaciones__pb2.TransferirDonacionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
