# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import eventos_pb2 as eventos__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in eventos_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EventosServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetEventos = channel.unary_unary(
                '/eventos.EventosService/GetEventos',
                request_serializer=eventos__pb2.Empty.SerializeToString,
                response_deserializer=eventos__pb2.ListEventosResponse.FromString,
                _registered_method=True)
        self.AltaEvento = channel.unary_unary(
                '/eventos.EventosService/AltaEvento',
                request_serializer=eventos__pb2.AltaEventoRequest.SerializeToString,
                response_deserializer=eventos__pb2.AltaEventoResponse.FromString,
                _registered_method=True)
        self.ModEvento = channel.unary_unary(
                '/eventos.EventosService/ModEvento',
                request_serializer=eventos__pb2.ModEventoRequest.SerializeToString,
                response_deserializer=eventos__pb2.ModEventoResponse.FromString,
                _registered_method=True)
        self.BajaEvento = channel.unary_unary(
                '/eventos.EventosService/BajaEvento',
                request_serializer=eventos__pb2.BajaEventoRequest.SerializeToString,
                response_deserializer=eventos__pb2.BajaEventoResponse.FromString,
                _registered_method=True)
        self.AgregarMiembro = channel.unary_unary(
                '/eventos.EventosService/AgregarMiembro',
                request_serializer=eventos__pb2.AsignarMiembroRequest.SerializeToString,
                response_deserializer=eventos__pb2.Empty.FromString,
                _registered_method=True)
        self.QuitarMiembro = channel.unary_unary(
                '/eventos.EventosService/QuitarMiembro',
                request_serializer=eventos__pb2.QuitarMiembroRequest.SerializeToString,
                response_deserializer=eventos__pb2.Empty.FromString,
                _registered_method=True)


class EventosServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetEventos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AltaEvento(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ModEvento(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BajaEvento(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AgregarMiembro(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QuitarMiembro(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EventosServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetEventos': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEventos,
                    request_deserializer=eventos__pb2.Empty.FromString,
                    response_serializer=eventos__pb2.ListEventosResponse.SerializeToString,
            ),
            'AltaEvento': grpc.unary_unary_rpc_method_handler(
                    servicer.AltaEvento,
                    request_deserializer=eventos__pb2.AltaEventoRequest.FromString,
                    response_serializer=eventos__pb2.AltaEventoResponse.SerializeToString,
            ),
            'ModEvento': grpc.unary_unary_rpc_method_handler(
                    servicer.ModEvento,
                    request_deserializer=eventos__pb2.ModEventoRequest.FromString,
                    response_serializer=eventos__pb2.ModEventoResponse.SerializeToString,
            ),
            'BajaEvento': grpc.unary_unary_rpc_method_handler(
                    servicer.BajaEvento,
                    request_deserializer=eventos__pb2.BajaEventoRequest.FromString,
                    response_serializer=eventos__pb2.BajaEventoResponse.SerializeToString,
            ),
            'AgregarMiembro': grpc.unary_unary_rpc_method_handler(
                    servicer.AgregarMiembro,
                    request_deserializer=eventos__pb2.AsignarMiembroRequest.FromString,
                    response_serializer=eventos__pb2.Empty.SerializeToString,
            ),
            'QuitarMiembro': grpc.unary_unary_rpc_method_handler(
                    servicer.QuitarMiembro,
                    request_deserializer=eventos__pb2.QuitarMiembroRequest.FromString,
                    response_serializer=eventos__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'eventos.EventosService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('eventos.EventosService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EventosService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetEventos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/eventos.EventosService/GetEventos',
            eventos__pb2.Empty.SerializeToString,
            eventos__pb2.ListEventosResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AltaEvento(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/eventos.EventosService/AltaEvento',
            eventos__pb2.AltaEventoRequest.SerializeToString,
            eventos__pb2.AltaEventoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ModEvento(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/eventos.EventosService/ModEvento',
            eventos__pb2.ModEventoRequest.SerializeToString,
            eventos__pb2.ModEventoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BajaEvento(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/eventos.EventosService/BajaEvento',
            eventos__pb2.BajaEventoRequest.SerializeToString,
            eventos__pb2.BajaEventoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AgregarMiembro(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/eventos.EventosService/AgregarMiembro',
            eventos__pb2.AsignarMiembroRequest.SerializeToString,
            eventos__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QuitarMiembro(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/eventos.EventosService/QuitarMiembro',
            eventos__pb2.QuitarMiembroRequest.SerializeToString,
            eventos__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
