# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import messages_pb2 as messages__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in messages_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MessagesServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AltaSolicitudDonacion = channel.unary_unary(
                '/messages.MessagesService/AltaSolicitudDonacion',
                request_serializer=messages__pb2.SolicitudDonacion.SerializeToString,
                response_deserializer=messages__pb2.RespuestaDonacion.FromString,
                _registered_method=True)
        self.RegistrarTransferencia = channel.unary_unary(
                '/messages.MessagesService/RegistrarTransferencia',
                request_serializer=messages__pb2.TransferenciaDonacion.SerializeToString,
                response_deserializer=messages__pb2.RespuestaDonacion.FromString,
                _registered_method=True)
        self.AltaOferta = channel.unary_unary(
                '/messages.MessagesService/AltaOferta',
                request_serializer=messages__pb2.OfertaDonacion.SerializeToString,
                response_deserializer=messages__pb2.RespuestaDonacion.FromString,
                _registered_method=True)
        self.BajaSolicitudDonacion = channel.unary_unary(
                '/messages.MessagesService/BajaSolicitudDonacion',
                request_serializer=messages__pb2.BajaSolicitud.SerializeToString,
                response_deserializer=messages__pb2.RespuestaDonacion.FromString,
                _registered_method=True)
        self.PublicarEventoExterno = channel.unary_unary(
                '/messages.MessagesService/PublicarEventoExterno',
                request_serializer=messages__pb2.EventoExterno.SerializeToString,
                response_deserializer=messages__pb2.RespuestaEvento.FromString,
                _registered_method=True)
        self.BajaEventoExterno = channel.unary_unary(
                '/messages.MessagesService/BajaEventoExterno',
                request_serializer=messages__pb2.BajaEvento.SerializeToString,
                response_deserializer=messages__pb2.RespuestaEvento.FromString,
                _registered_method=True)
        self.RegistrarAdhesionEvento = channel.unary_unary(
                '/messages.MessagesService/RegistrarAdhesionEvento',
                request_serializer=messages__pb2.AdhesionEvento.SerializeToString,
                response_deserializer=messages__pb2.RespuestaEvento.FromString,
                _registered_method=True)


class MessagesServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AltaSolicitudDonacion(self, request, context):
        """---- Donaciones ----
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegistrarTransferencia(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AltaOferta(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BajaSolicitudDonacion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PublicarEventoExterno(self, request, context):
        """---- Eventos ----
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BajaEventoExterno(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegistrarAdhesionEvento(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MessagesServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AltaSolicitudDonacion': grpc.unary_unary_rpc_method_handler(
                    servicer.AltaSolicitudDonacion,
                    request_deserializer=messages__pb2.SolicitudDonacion.FromString,
                    response_serializer=messages__pb2.RespuestaDonacion.SerializeToString,
            ),
            'RegistrarTransferencia': grpc.unary_unary_rpc_method_handler(
                    servicer.RegistrarTransferencia,
                    request_deserializer=messages__pb2.TransferenciaDonacion.FromString,
                    response_serializer=messages__pb2.RespuestaDonacion.SerializeToString,
            ),
            'AltaOferta': grpc.unary_unary_rpc_method_handler(
                    servicer.AltaOferta,
                    request_deserializer=messages__pb2.OfertaDonacion.FromString,
                    response_serializer=messages__pb2.RespuestaDonacion.SerializeToString,
            ),
            'BajaSolicitudDonacion': grpc.unary_unary_rpc_method_handler(
                    servicer.BajaSolicitudDonacion,
                    request_deserializer=messages__pb2.BajaSolicitud.FromString,
                    response_serializer=messages__pb2.RespuestaDonacion.SerializeToString,
            ),
            'PublicarEventoExterno': grpc.unary_unary_rpc_method_handler(
                    servicer.PublicarEventoExterno,
                    request_deserializer=messages__pb2.EventoExterno.FromString,
                    response_serializer=messages__pb2.RespuestaEvento.SerializeToString,
            ),
            'BajaEventoExterno': grpc.unary_unary_rpc_method_handler(
                    servicer.BajaEventoExterno,
                    request_deserializer=messages__pb2.BajaEvento.FromString,
                    response_serializer=messages__pb2.RespuestaEvento.SerializeToString,
            ),
            'RegistrarAdhesionEvento': grpc.unary_unary_rpc_method_handler(
                    servicer.RegistrarAdhesionEvento,
                    request_deserializer=messages__pb2.AdhesionEvento.FromString,
                    response_serializer=messages__pb2.RespuestaEvento.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'messages.MessagesService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('messages.MessagesService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MessagesService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AltaSolicitudDonacion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/messages.MessagesService/AltaSolicitudDonacion',
            messages__pb2.SolicitudDonacion.SerializeToString,
            messages__pb2.RespuestaDonacion.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegistrarTransferencia(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/messages.MessagesService/RegistrarTransferencia',
            messages__pb2.TransferenciaDonacion.SerializeToString,
            messages__pb2.RespuestaDonacion.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AltaOferta(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/messages.MessagesService/AltaOferta',
            messages__pb2.OfertaDonacion.SerializeToString,
            messages__pb2.RespuestaDonacion.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BajaSolicitudDonacion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/messages.MessagesService/BajaSolicitudDonacion',
            messages__pb2.BajaSolicitud.SerializeToString,
            messages__pb2.RespuestaDonacion.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PublicarEventoExterno(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/messages.MessagesService/PublicarEventoExterno',
            messages__pb2.EventoExterno.SerializeToString,
            messages__pb2.RespuestaEvento.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BajaEventoExterno(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/messages.MessagesService/BajaEventoExterno',
            messages__pb2.BajaEvento.SerializeToString,
            messages__pb2.RespuestaEvento.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegistrarAdhesionEvento(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/messages.MessagesService/RegistrarAdhesionEvento',
            messages__pb2.AdhesionEvento.SerializeToString,
            messages__pb2.RespuestaEvento.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
