# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rol.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'rol.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\trol.proto\x12\x05roles\"\x07\n\x05\x45mpty\"$\n\x03Rol\x12\r\n\x05idrol\x18\x01 \x01(\x03\x12\x0e\n\x06nombre\x18\x02 \x01(\t\",\n\x0fRolListResponse\x12\x19\n\x05roles\x18\x01 \x03(\x0b\x32\n.roles.Rol2g\n\nRolService\x12\x30\n\x08GetRoles\x12\x0c.roles.Empty\x1a\x16.roles.RolListResponse\x12\'\n\x0bupdateRoles\x12\n.roles.Rol\x1a\x0c.roles.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rol_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=20
  _globals['_EMPTY']._serialized_end=27
  _globals['_ROL']._serialized_start=29
  _globals['_ROL']._serialized_end=65
  _globals['_ROLLISTRESPONSE']._serialized_start=67
  _globals['_ROLLISTRESPONSE']._serialized_end=111
  _globals['_ROLSERVICE']._serialized_start=113
  _globals['_ROLSERVICE']._serialized_end=216
# @@protoc_insertion_point(module_scope)
