# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import rol_pb2 as rol__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in rol_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RolServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRoles = channel.unary_unary(
                '/roles.RolService/GetRoles',
                request_serializer=rol__pb2.Empty.SerializeToString,
                response_deserializer=rol__pb2.RolListResponse.FromString,
                _registered_method=True)
        self.updateRoles = channel.unary_unary(
                '/roles.RolService/updateRoles',
                request_serializer=rol__pb2.Rol.SerializeToString,
                response_deserializer=rol__pb2.Empty.FromString,
                _registered_method=True)


class RolServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetRoles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def updateRoles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RolServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRoles': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRoles,
                    request_deserializer=rol__pb2.Empty.FromString,
                    response_serializer=rol__pb2.RolListResponse.SerializeToString,
            ),
            'updateRoles': grpc.unary_unary_rpc_method_handler(
                    servicer.updateRoles,
                    request_deserializer=rol__pb2.Rol.FromString,
                    response_serializer=rol__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'roles.RolService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('roles.RolService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RolService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetRoles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/roles.RolService/GetRoles',
            rol__pb2.Empty.SerializeToString,
            rol__pb2.RolListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def updateRoles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/roles.RolService/updateRoles',
            rol__pb2.Rol.SerializeToString,
            rol__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
