# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: session.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'session.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import usuarios_pb2 as usuarios__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rsession.proto\x12\x07session\x1a\x0eusuarios.proto\"4\n\x0cLoginRequest\x12\x15\n\rusuario_email\x18\x01 \x01(\t\x12\r\n\x05\x63lave\x18\x02 \x01(\t\"T\n\rLoginResponse\x12\x0e\n\x06suceso\x18\x01 \x01(\x08\x12\'\n\x07usuario\x18\x02 \x01(\x0b\x32\x11.usuarios.UsuarioH\x00\x88\x01\x01\x42\n\n\x08_usuario\"\r\n\x0bInfoRequest\"E\n\x0cInfoResponse\x12\x11\n\tidusuario\x18\x01 \x01(\x03\x12\x15\n\rnombreUsuario\x18\x02 \x01(\t\x12\x0b\n\x03rol\x18\x03 \x01(\x03\x32\x82\x01\n\x0cLoginService\x12\x36\n\x05Login\x12\x15.session.LoginRequest\x1a\x16.session.LoginResponse\x12:\n\x0bObtenerInfo\x12\x14.session.InfoRequest\x1a\x15.session.InfoResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'session_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGINREQUEST']._serialized_start=42
  _globals['_LOGINREQUEST']._serialized_end=94
  _globals['_LOGINRESPONSE']._serialized_start=96
  _globals['_LOGINRESPONSE']._serialized_end=180
  _globals['_INFOREQUEST']._serialized_start=182
  _globals['_INFOREQUEST']._serialized_end=195
  _globals['_INFORESPONSE']._serialized_start=197
  _globals['_INFORESPONSE']._serialized_end=266
  _globals['_LOGINSERVICE']._serialized_start=269
  _globals['_LOGINSERVICE']._serialized_end=399
# @@protoc_insertion_point(module_scope)
