# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: usuarios.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'usuarios.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eusuarios.proto\x12\x08usuarios\"\xc0\x01\n\x07Usuario\x12\x11\n\tidusuario\x18\x01 \x01(\x03\x12\x15\n\rnombreUsuario\x18\x02 \x01(\t\x12\x0e\n\x06nombre\x18\x03 \x01(\t\x12\x10\n\x08\x61pellido\x18\x04 \x01(\t\x12\x12\n\x05\x65mail\x18\x05 \x01(\tH\x00\x88\x01\x01\x12\x0b\n\x03rol\x18\x06 \x01(\x03\x12\x12\n\x05\x63lave\x18\x07 \x01(\tH\x01\x88\x01\x01\x12\x10\n\x08telefono\x18\x08 \x01(\t\x12\x0e\n\x06\x61\x63tivo\x18\t \x01(\x08\x42\x08\n\x06_emailB\x08\n\x06_clave\"8\n\x12\x41ltaUsuarioRequest\x12\"\n\x07usuario\x18\x01 \x01(\x0b\x32\x11.usuarios.Usuario\"%\n\x13\x41ltaUsuarioResponse\x12\x0e\n\x06suceso\x18\x01 \x01(\x08\"7\n\x11ModUsuarioRequest\x12\"\n\x07usuario\x18\x01 \x01(\x0b\x32\x11.usuarios.Usuario\"$\n\x12ModUsuarioResponse\x12\x0e\n\x06suceso\x18\x01 \x01(\x08\"\'\n\x12\x42\x61jaUsuarioRequest\x12\x11\n\tidusuario\x18\x01 \x01(\x03\"%\n\x13\x42\x61jaUsuarioResponse\x12\x0e\n\x06suceso\x18\x01 \x01(\x08\"\x07\n\x05\x45mpty\":\n\x13UsuarioListResponse\x12#\n\x08usuarios\x18\x01 \x03(\x0b\x32\x11.usuarios.Usuario2\xb0\x02\n\x0eUsuarioService\x12=\n\x0bGetUsuarios\x12\x0f.usuarios.Empty\x1a\x1d.usuarios.UsuarioListResponse\x12J\n\x0b\x41ltaUsuario\x12\x1c.usuarios.AltaUsuarioRequest\x1a\x1d.usuarios.AltaUsuarioResponse\x12G\n\nModUsuario\x12\x1b.usuarios.ModUsuarioRequest\x1a\x1c.usuarios.ModUsuarioResponse\x12J\n\x0b\x42\x61jaUsuario\x12\x1c.usuarios.BajaUsuarioRequest\x1a\x1d.usuarios.BajaUsuarioResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'usuarios_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USUARIO']._serialized_start=29
  _globals['_USUARIO']._serialized_end=221
  _globals['_ALTAUSUARIOREQUEST']._serialized_start=223
  _globals['_ALTAUSUARIOREQUEST']._serialized_end=279
  _globals['_ALTAUSUARIORESPONSE']._serialized_start=281
  _globals['_ALTAUSUARIORESPONSE']._serialized_end=318
  _globals['_MODUSUARIOREQUEST']._serialized_start=320
  _globals['_MODUSUARIOREQUEST']._serialized_end=375
  _globals['_MODUSUARIORESPONSE']._serialized_start=377
  _globals['_MODUSUARIORESPONSE']._serialized_end=413
  _globals['_BAJAUSUARIOREQUEST']._serialized_start=415
  _globals['_BAJAUSUARIOREQUEST']._serialized_end=454
  _globals['_BAJAUSUARIORESPONSE']._serialized_start=456
  _globals['_BAJAUSUARIORESPONSE']._serialized_end=493
  _globals['_EMPTY']._serialized_start=495
  _globals['_EMPTY']._serialized_end=502
  _globals['_USUARIOLISTRESPONSE']._serialized_start=504
  _globals['_USUARIOLISTRESPONSE']._serialized_end=562
  _globals['_USUARIOSERVICE']._serialized_start=565
  _globals['_USUARIOSERVICE']._serialized_end=869
# @@protoc_insertion_point(module_scope)
