# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: usuarios.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'usuarios.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eusuarios.proto\x12\x08usuarios\x1a\x1bgoogle/protobuf/empty.proto\"\xa2\x01\n\x07Usuario\x12\x11\n\tidusuario\x18\x01 \x01(\x05\x12\x15\n\rnombreUsuario\x18\x02 \x01(\t\x12\x0e\n\x06nombre\x18\x03 \x01(\t\x12\x10\n\x08\x61pellido\x18\x04 \x01(\t\x12\r\n\x05\x65mail\x18\x05 \x01(\t\x12\x0b\n\x03rol\x18\x06 \x01(\x05\x12\r\n\x05\x63lave\x18\x07 \x01(\t\x12\x10\n\x08telefono\x18\x08 \x01(\t\x12\x0e\n\x06\x61\x63tivo\x18\t \x01(\x08\"4\n\rListaUsuarios\x12#\n\x08usuarios\x18\x01 \x03(\x0b\x32\x11.usuarios.Usuario2P\n\x0eUsuarioService\x12>\n\x0bGetUsuarios\x12\x16.google.protobuf.Empty\x1a\x17.usuarios.ListaUsuariosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'usuarios_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USUARIO']._serialized_start=58
  _globals['_USUARIO']._serialized_end=220
  _globals['_LISTAUSUARIOS']._serialized_start=222
  _globals['_LISTAUSUARIOS']._serialized_end=274
  _globals['_USUARIOSERVICE']._serialized_start=276
  _globals['_USUARIOSERVICE']._serialized_end=356
# @@protoc_insertion_point(module_scope)
