# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import usuarios_pb2 as usuarios__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in usuarios_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UsuarioServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUsuario = channel.unary_unary(
                '/usuarios.UsuarioService/GetUsuario',
                request_serializer=usuarios__pb2.UsuarioRequest.SerializeToString,
                response_deserializer=usuarios__pb2.UsuarioResponse.FromString,
                _registered_method=True)
        self.GetUsuarios = channel.unary_unary(
                '/usuarios.UsuarioService/GetUsuarios',
                request_serializer=usuarios__pb2.Empty.SerializeToString,
                response_deserializer=usuarios__pb2.UsuarioListResponse.FromString,
                _registered_method=True)
        self.AltaUsuario = channel.unary_unary(
                '/usuarios.UsuarioService/AltaUsuario',
                request_serializer=usuarios__pb2.AltaUsuarioRequest.SerializeToString,
                response_deserializer=usuarios__pb2.AltaUsuarioResponse.FromString,
                _registered_method=True)
        self.ModUsuario = channel.unary_unary(
                '/usuarios.UsuarioService/ModUsuario',
                request_serializer=usuarios__pb2.ModUsuarioRequest.SerializeToString,
                response_deserializer=usuarios__pb2.ModUsuarioResponse.FromString,
                _registered_method=True)
        self.BajaUsuario = channel.unary_unary(
                '/usuarios.UsuarioService/BajaUsuario',
                request_serializer=usuarios__pb2.BajaUsuarioRequest.SerializeToString,
                response_deserializer=usuarios__pb2.BajaUsuarioResponse.FromString,
                _registered_method=True)


class UsuarioServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetUsuario(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUsuarios(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AltaUsuario(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ModUsuario(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BajaUsuario(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UsuarioServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUsuario': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUsuario,
                    request_deserializer=usuarios__pb2.UsuarioRequest.FromString,
                    response_serializer=usuarios__pb2.UsuarioResponse.SerializeToString,
            ),
            'GetUsuarios': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUsuarios,
                    request_deserializer=usuarios__pb2.Empty.FromString,
                    response_serializer=usuarios__pb2.UsuarioListResponse.SerializeToString,
            ),
            'AltaUsuario': grpc.unary_unary_rpc_method_handler(
                    servicer.AltaUsuario,
                    request_deserializer=usuarios__pb2.AltaUsuarioRequest.FromString,
                    response_serializer=usuarios__pb2.AltaUsuarioResponse.SerializeToString,
            ),
            'ModUsuario': grpc.unary_unary_rpc_method_handler(
                    servicer.ModUsuario,
                    request_deserializer=usuarios__pb2.ModUsuarioRequest.FromString,
                    response_serializer=usuarios__pb2.ModUsuarioResponse.SerializeToString,
            ),
            'BajaUsuario': grpc.unary_unary_rpc_method_handler(
                    servicer.BajaUsuario,
                    request_deserializer=usuarios__pb2.BajaUsuarioRequest.FromString,
                    response_serializer=usuarios__pb2.BajaUsuarioResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'usuarios.UsuarioService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('usuarios.UsuarioService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UsuarioService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetUsuario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/usuarios.UsuarioService/GetUsuario',
            usuarios__pb2.UsuarioRequest.SerializeToString,
            usuarios__pb2.UsuarioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUsuarios(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/usuarios.UsuarioService/GetUsuarios',
            usuarios__pb2.Empty.SerializeToString,
            usuarios__pb2.UsuarioListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AltaUsuario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/usuarios.UsuarioService/AltaUsuario',
            usuarios__pb2.AltaUsuarioRequest.SerializeToString,
            usuarios__pb2.AltaUsuarioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ModUsuario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/usuarios.UsuarioService/ModUsuario',
            usuarios__pb2.ModUsuarioRequest.SerializeToString,
            usuarios__pb2.ModUsuarioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BajaUsuario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/usuarios.UsuarioService/BajaUsuario',
            usuarios__pb2.BajaUsuarioRequest.SerializeToString,
            usuarios__pb2.BajaUsuarioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
